# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('droneExchange', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfootage',
            old_name='link',
            new_name='footage',
        ),
    ]
