# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('droneExchange', '0002_auto_20170828_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfootage',
            old_name='footage',
            new_name='link',
        ),
    ]
