# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droneExchange', '0003_auto_20170828_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfootage',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
