# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('droneExchange', '0005_city_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='details',
            name='person',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
